# Generated by Django 4.2.4 on 2023-08-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habbits',
            name='title',
        ),
    ]
