# Generated by Django 4.2.4 on 2023-08-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_habbits_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habbits',
            name='reward',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='вознаграждение'),
        ),
        migrations.AlterField(
            model_name='habbits',
            name='times',
            field=models.TimeField(default='00:00', verbose_name='время начала выполнения'),
        ),
    ]
