# Generated by Django 4.2.4 on 2023-08-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habbits_reward_alter_habbits_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habbits',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Признак публичности'),
        ),
    ]
